# Generated by Django 5.0.6 on 2024-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_flan_flans_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
